# Generated by Django 5.2.10 on 2026-02-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_stripe_price_id_course_stripe_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='last_notification_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
